# Global constants file

# main file
KEYS = ('Up', 'Down', 'w', 's')
TRACER_DEFAULT_VALUE = 0
SLEEP_TIME = 1 / 100000000000000000
PLAY_ACCEPT_INPUT = 'y'
PLAY_DENY_INPUT = 'n'

# arena file
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
WINDOW_TITLE = 'Pong'
PROMPT_TITLE = "Play"
PROMPT_TXT = 'Do you want to play the game (y/n)?'
NET_COORDINATES = [(0, 250), (0, 200), (0, 150), (0, 100), (0, 50), (0, 0), (0, -50), (0, -100),
                   (0, -150), (0, -200), (0, -250), ]
NET_SEGMENT_WIDTH = 2
NET_SEGMENT_LENGTH = 0.25

# paddle file
PADDLE_SEGMENT_WIDTH = 0.5
R_PADDLE_COORDINATES = [(380, 20), (380, 0), (380, -20)]
L_PADDLE_COORDINATES = [(-380, 20), (-380, 0), (-380, -20)]
PADDLE_DIRECTION_NEGATION_VALUE = -1
PADDLE_DIRECTION_MAINTAIN_VALUE = 1
PADDLE_CHANCE_DOWN_RANGE = 0
PADDLE_CHANCE_UP_RANGE_EASY_LEVEL = 15
PADDLE_CHANCE_VALUE = 0
PADDLE_SEGMENTS_YCOR_SPACING = 20
PADDLE_CHANGING_DIRECTION_YCOR_VALUE = 0
PADDLE_SEGMENTS_YCOR_LIMIT = 380
BALL_DISTANCE = 10
POSITIVE_Y_DIRECTION = 1
NEUTRAL_Y_DIRECTION = 0
NEGATIVE_Y_DIRECTION = -1

# segment file
SEGMENT_STEPS = 20
SEGMENT_SHAPE = 'square'
SEGMENT_COLOR = 'black'
SEGMENT_DEFAULT_WIDTH = 1
SEGMENT_DEFAULT_LENGTH = 1
SEGMENT_DEFAULT_DIRECTION = 1
SEGMENT_CEILING_HIT_POINT = (SCREEN_HEIGHT / 2)
SEGMENT_FLOOR_HIT_POINT = -(SCREEN_HEIGHT / 2)

# ball file
BALL_SHAPE = 'circle'
BALL_STRETCH_WID = 0.5
BALL_STRETCH_LEN = 0.5
BALL_DIRECTION_DEFAULT_VALUE = 1
BALL_CEILING_HIT_LIMIT = (SCREEN_HEIGHT / 2 - 10)
BALL_FLOOR_HIT_LIMIT = -(SCREEN_HEIGHT / 2 - 10)
BALL_DEFAULT_SPEED = 1.2
BALL_INCREASE_SPEED_VALUE = 0.2
RIGHT_GOAL_HIT = (SCREEN_WIDTH / 2)
LEFT_GOAL_HIT = -(SCREEN_WIDTH / 2)
BALL_CENTERING_DEFAULT_POSITION = (0, 0)
BALL_DIRECTION_NEGATION_VALUE = -1
BALL_DIRECTION_MAINTAIN_VALUE = 1

# scoreboard file
DEFAULT_SCORE = -1
SCORE_INCREASE_VALUE = 1
SCORE_TXT = "Score: "
SCORE_TXT_ALIGNMENT = 'left'
SCORE_TXT_FONT = ('Erbos Draco 1st Open NBP', 30, 'normal')
SCORE_TXT_DEFAULT_POSITION = (-(SCREEN_WIDTH / 2 - 40), (SCREEN_HEIGHT / 2 - 60))
R_SCORE_POSITION = (50, (SCREEN_HEIGHT / 2 - 50))
L_SCORE_POSITION = (-80, (SCREEN_HEIGHT / 2 - 50))
GAME_OVER_TXT = 'GAME OVER'
GAME_OVER_ALIGNMENT = 'center'
GAME_OVER_FONT = ('Snake Game Demo', 50, 'bold')
GAME_OVER_COLOR = 'red'
GAME_OVER_POSITION = (0, (SCREEN_HEIGHT / 2 - 200))
GAME_OVER_SCORE = 10

# difficulty class
BALL_INCREASE_SPEED_VALUES = (0.5, 1, 1.5)
DIFFICULTY_PROMPT_MSG = "Choose a difficulty (easy: 1, medium: 2 hard: 3): "
DIFFICULTY_PROMPT_TITLE = "Difficulty"
DIFFICULTY_PROMPT_MSG_ERROR = "Please choose a proper difficulty (easy, medium, hard): "
PADDLE_CHANCE_LEVELS_VALUES = [15, 10, 5]
PADDLE_CHANCE_DEFAULT_VALUE = PADDLE_CHANCE_LEVELS_VALUES[0]
DIFFICULTY_LEVELS_VALUES = [1, 2, 3]

# playing mode class
SINGLE_MODE_DEFAULT_VALUE = True
SINGLE_MODE_NEGATE_VALUE = False
PLAYING_MODE_PROMPT_TITLE = 'Playing Mode'
PLAYING_MODE_PROMPT_TXT = "Choose a playing mode (1:single, 2:two):"
PLAYING_MODE_FIRST_INDX = 1
PLAYING_MODE_SECOND_INDX = 2
