# Global constants file

# main file
KEYS = ('Up', 'Down', 'w', 's')

# arena file
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
WINDOW_TITLE = 'Pong'
PROMPT_TITLE = "Play"
PROMPT_TXT = 'Do you want to play the game (y/n)?'
NET_COORDINATES = [(0, 250), (0, 200), (0, 150), (0, 100), (0, 50), (0, 0), (0, -50), (0, -100),
                   (0, -150), (0, -200), (0, -250), ]
NET_SEGMENT_WIDTH = 2
NET_SEGMENT_LENGTH = 0.25

# paddle file
PADDLE_SEGMENT_WIDTH = 0.5
R_PADDLE_COORDINATES = [(380, 20), (380, 0), (380, -20)]
L_PADDLE_COORDINATES = [(-380, 20), (-380, 0), (-380, -20)]

# segment file
SEGMENT_STEPS = 20
SEGMENT_CEILING_HIT_POINT = (SCREEN_HEIGHT / 2)
SEGMENT_FLOOR_HIT_POINT = -(SCREEN_HEIGHT / 2)

# ball file
BALL_SHAPE = 'circle'
BALL_STRETCH_WID = 0.5
BALL_STRETCH_LEN = 0.5
BALL_DIRECTION_DEFAULT_VALUE = 1
BALL_CEILING_HIT_LIMIT = (SCREEN_HEIGHT / 2 - 10)
BALL_FLOOR_HIT_LIMIT = -(SCREEN_HEIGHT / 2 - 10)
BALL_STEPS = 1
RIGHT_GOAL_HIT = (SCREEN_WIDTH / 2)
LEFT_GOAL_HIT = -(SCREEN_WIDTH / 2)

# scoreboard file
DEFAULT_SCORE = -1
SCORE_INCREASE_VALUE = 1
SCORE_TXT = "Score: "
SCORE_TXT_ALIGNMENT = 'left'
SCORE_TXT_FONT = ('Erbos Draco 1st Open NBP', 30, 'normal')
SCORE_TXT_DEFAULT_POSITION = (-(SCREEN_WIDTH / 2 - 40), (SCREEN_HEIGHT / 2 - 60))
R_SCORE_POSITION = (60, (SCREEN_HEIGHT / 2 - 50))
L_SCORE_POSITION = (-80, (SCREEN_HEIGHT / 2 - 50))
